# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('desc', models.CharField(db_index=True, max_length=100)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ('-time',),
                'verbose_name': '\u041f\u043e\u0434\u0456\u0457',
                'verbose_name_plural': '\u041f\u043e\u0434\u0456\u0457',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('title', models.TextField(db_index=True, max_length=250)),
                ('description', models.TextField(verbose_name='O\u043f\u0438\u0441 \u043f\u043e\u0434\u0456\u0457')),
                ('more_description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': ' \u041d\u043e\u0432\u0438\u043d\u0438',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='photoes/')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ManyToManyField(to='home.Photo'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['time'], name='home_events_time_a00859_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
