# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
