# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180619_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('-time',), 'verbose_name': '\u041f\u043e\u0434\u0456\u0457', 'verbose_name_plural': '\u041f\u043e\u0434\u0456\u0457'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f', 'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name_plural': ' \u041d\u043e\u0432\u0438\u043d\u0438'},
        ),
        migrations.AlterField(
            model_name='carusel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['time'], name='home_events_time_a00859_idx'),
        ),
    ]
