# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180705_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
